id: IAE9D7499
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:15:50+00:00'
last_modified: '2022-06-16T04:51:48.462089+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27310
  title: ས་སྐྱའི་གདུང་རབས་ངོ་མཚར་རིན་ཆེན་ཀུན་འཕེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4ACD:
      image_group_id: I4279
      title: ''
      total_pages: 878
      order: 1
      base_file: 4ACD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
